# version: 2.1
# jobs:
#    build:
#      docker:
#        - image: circleci/node:latest
#      steps:
#        - checkout
#        - run: npm install
#        - run: CI=true npm run build
#    test:
#      docker:
#        - image: circleci/node:latest
#      steps:
#        - checkout
#        - run: npm install
#        - run: npm run test
#    hithere:
#      docker:
#        - image: circleci/node:latest
#      steps:
#        - checkout
#        - run: echo "Hellloooo!"
# workflows:
#   version: 2
#   build-test-and-lint:
#     jobs:
#       - build
#       - hithere
#       - test:
#           requires:
#             - hithere

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  bobby:
  # Declare a dependency on the welcome-orb
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "A bobby hello"
# Orchestrate or schedule a set of jobs
  sally:
  # Declare a dependency on the welcome-orb
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "A sally hello"
workflows:
  # Name the workflow "welcome"
  version: 2.1
  bobby_sally:
    # Run the welcome/run job in its own container
    jobs:
      - bobby
      - sally
